--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gateway
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: jacopomassa97/gateway:latest
        ports:
          - containerPort: 5000
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: math-service
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: math-service
  template:
    metadata:
      labels:
        app: math-service
    spec:
      containers:
      - name: math-service
        image: jacopomassa97/math_py:latest
        ports:
          - containerPort: 5000
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: string-service
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: string-service
  template:
    metadata:
      labels:
        app: string-service
    spec:
      containers:
      - name: string-service
        image: jacopomassa97/string_rust:latest
        ports:
          - containerPort: 5000